language: cpp

sudo: required

notifications:
  email: false

before_script:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- sudo apt-get -y install g++-9

script:
- cd ${TRAVIS_BUILD_DIR}
- g++-9 --version
- make
