language: cpp

sudo: required

notifications:
  email: false

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_install:
  # support minted LaTeX package
  - sudo apt-get install python-pygments

before_script:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -y
- sudo apt-get -y install g++-9

script:
- cd ${TRAVIS_BUILD_DIR}
- g++-9 --version

# build executables from C++ sources
- make all

# test executables
- make testall

# build PDF report from LaTeX sources
- (cd report && texliveonfly --arguments='-shell-escape' main.tex)
