OUT_DIR=out
F_WARNINGS=-Wall -Wextra
F_OPTIMIZATION=-O3
FLAGS=${F_OPTIMIZATION} ${F_WARNINGS} -std=c++17
MAINFILE=main.cpp

KRUSKAL_SIMPLE=kruskalSimple
KRUSKAL_SIMPLE_DIR=KruskalSimple
KRUSKAL_SIMPLE_OUT_FILENAME=kruskalSimple.out

KRUSKAL_UNION_FIND=kruskalUnionFind
KRUSKAL_UNION_FIND_DIR=KruskalUnionFind
KRUSKAL_UNION_FIND_OUT_FILENAME=kruskalUnionFind.out

PRIM_BINARY_HEAP=primBinaryHeap
PRIM_BINARY_HEAP_DIR=PrimBinaryHeap
PRIM_BINARY_HEAP_OUT_FILENAME=primBinaryHeap.out

all: ${KRUSKAL_SIMPLE} ${KRUSKAL_UNION_FIND} ${PRIM_BINARY_HEAP}

${KRUSKAL_SIMPLE}: ensureOutDirCreated
	g++ ${FLAGS} ${KRUSKAL_SIMPLE_DIR}/${MAINFILE} -o ${OUT_DIR}/${KRUSKAL_SIMPLE_OUT_FILENAME}

${KRUSKAL_UNION_FIND}: ensureOutDirCreated
	g++ ${FLAGS} ${KRUSKAL_UNION_FIND_DIR}/${MAINFILE} -o ${OUT_DIR}/${KRUSKAL_UNION_FIND_OUT_FILENAME}

${PRIM_BINARY_HEAP}: ensureOutDirCreated
	g++ ${FLAGS} ${PRIM_BINARY_HEAP_DIR}/${MAINFILE} -o ${OUT_DIR}/${PRIM_BINARY_HEAP_OUT_FILENAME}

ensureOutDirCreated:
	mkdir -p out

.PHONY: all ${KRUSKAL_SIMPLE} ${KRUSKAL_UNION_FIND} ${PRIM_BINARY_HEAP} ensureOutDirCreated